### ISSUE TITLE
VoidTypeName should not exist

### ISSUE THREAD

**Issue by eamonnmcmanus** [square/javawriter#116]
As suggested in https://github.com/square/javawriter/pull/109, `VoidTypeName` suggests that `void` is a type, which it is not, and allows users to accidentally ask for void fields and parameters. The only place where `void` can appear is to specify the result of a method in `MethodWriter`, when the method does not return a value. As an alternative design, we could delete `VoidTypeName` and instead have the `returnType` parameter of the `MethodWriter` constructor be an `Optional<TypeName>`; or have a second constructor that omits the `returnType` for use when the method is void; or introduce a new supertype of `TypeName` called `MethodReturn`, with a new class `VoidReturn` that is also a subclass of `TypeNameOrVoid`.

**Comment by swankjesse** [comment]
No action to take here with the current codebase.
