### ISSUE TITLE
Consider BlockWriter emitting braces.

### ISSUE THREAD

**Issue by JakeWharton** [square/javawriter#134]
I think `BlockWriter` might be more useful if it was in control if emitting braces. This is a trivial change for methods and ctors, but I think the value is in user snippets as well.

For example,
```
if (thing) %s
```
Could take a `BlockWriter` and emit
```java
if (thing) {
  doSomething();
  doSomethingElse();
  return true;
}
```
This would work well for `switch` as well:
```
case "hello": %s
case "hi": %s
```
Could emit:
```java
case "hello": {
  String name = getName();
  return "Hello, " + name;
}
case "hi": {
  String name = getName();
  return "Hi, " + name;
}
```

**Comment by swankjesse** [comment]
To be addressed by https://github.com/square/javawriter/issues/171
