### ISSUE TITLE
AnnotationWriter has weird methods

### ISSUE THREAD

**Issue by JakeWharton** [square/javawriter#145]
```
setValue(String)
setMember(String, int)
setMember(String, String)
```
At the very least I think we want:
```
setValue(Snippet)
setMember(String, Snippet)
```
so that you can embed class references.

The `int`-overload is strange because I almost then want a `TypeName` overload for convenience. Not sure where the balance lies between convenience and absolute correctness.

**Comment by swankjesse** [comment]
Closed by https://github.com/square/javawriter/pull/166
