### ISSUE TITLE
Version 3.0 Working Spec

### ISSUE THREAD

**Issue by JakeWharton** [square/javawriter#51]
This issue will serve as a working space for what a potential version 3.0 would look like with a new, more dynamic, and more powerful API.

## High-Level Goals

 * The ability to defer type compression (imports) until emission.
 * Distinct code blocks as objects for composition.
 * _And more, probably..._

## Deferred Type Compression

Currently, type compression via imports requires knowledge of all types up before the body of the file. In practice, this usually requires an awkward two-pass approach where you determine the imports based on a pass of dynamic contents and then emit the body based on a second pass.

The goal of this is to always emit fully-qualified types from the API and rely on a post-compression phase for emitting imports.

There are multiple ways to approach this. A non-exhaustive list:
 * Type location-aware parsing of code statements combined with type parameters.
 * Method which wraps a type in a token that can later be replaced.
 * Code blocks which are aware of which types they contain. _(see below)_

## Code Block Objects

Objects which represents pieces of code lend themselves naturally to writing emission code in Java. The wins should hopefully be fairly obvious.

There is a potential for API explosion here to cover the diversity of the Java language. A potential also exists for adding an unacceptable amount of boilerplate to the API.

**Comment by swankjesse** [comment]
I'm closing this working spec issue.

Deferred type compression is done.

Code block objects are here:
https://github.com/square/javawriter/issues/171
