### ISSUE TITLE
Add support for nested annotations

### ISSUE THREAD

**Issue by Zubnix** [square/javawriter#62]
Currently emitAnnotation will do a toString() on the value of an annotation attribute. However this becomes a nuisance if the value itself is an annotation instance with its own values.

Is there perhaps a technique (and if not please add it!) to easily define a new annotation as the value of an emitted annotation, that would function in the same way as an emitted annotation?

**Comment by swankjesse** [comment]
Implemented here: https://github.com/square/javawriter/pull/166
