### ISSUE TITLE
Export google proposal for jw3 to github, so we can comment and do diffs/prs, etc.

### ISSUE THREAD

**Issue by cgruber** [square/javawriter#83]
I'm now in the process, but this is a tracking bug.

Question for @JakeWharton, @swankjesse, @gk5885 - are we wanting square/javawriter to be the source of this?  In this case, I'll make sure that google/javawriter is a fork of square/javawriter, and we do pulls that way.  Or do we wnat to go the other direction, or what?  I'm ok with any of it, just want to know which way to orient these repos.

**Comment by swankjesse** [comment]
This is done.
